CarRentt/Areas/Admin/Controllers/GestionVoituresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarRentt.Models;

namespace CarRentt.Areas.Admin.Controllers
{
    [Authorize(Roles = "admins")]
    public class GestionVoituresController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/Voitures
        public ActionResult Index()
        {
            var voitures = db.Voitures.Include(v => v.Modele);
            return View(voitures.ToList());
        }

        // GET: Admin/Voitures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Voiture voiture = db.Voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            return View(voiture);
        }

        // GET: Admin/Voitures/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Voitures/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Voiture voiture, HttpPostedFileBase img, int MID)
        {
            string path = Path.Combine(Server.MapPath("~/Image/voitures"), img.FileName);
            img.SaveAs(path);
            voiture.Image = img.FileName;
            voiture.IsAvailable = 1;
            voiture.ModeleID = MID;
            db.Voitures.Add(voiture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Admin/Voitures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Voiture voiture = db.Voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            ViewBag.ModeleID = new SelectList(db.Modeles, "ModeleID", "SerieVoiture", voiture.ModeleID);
            return View(voiture);
        }

        // POST: Admin/Voitures/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VoitureID,Matricule,DateDeMiseEnCirculation,TypeCarburant,PrixJournaliere,Image,ModeleID,IsAvailable")] Voiture voiture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(voiture).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ModeleID = new SelectList(db.Modeles, "ModeleID", "SerieVoiture", voiture.ModeleID);
            return View(voiture);
        }

        // GET: Admin/Voitures/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Voiture voiture = db.Voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            return View(voiture);
        }

        // POST: Admin/Voitures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Voiture voiture = db.Voitures.Find(id);
            db.Voitures.Remove(voiture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
         public ActionResult Stocker(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Voiture voiture = db.Voitures.Find(id);
            if (voiture == null)
            {
                return HttpNotFound();
            }
            voiture.IsAvailable = 1;
            db.Entry(voiture).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CarRentt/Areas/Admin/Views/GestionVoitures/Create.cshtml
@model CarRentt.Models.Voiture

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "GestionVoitures", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Voiture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Matricule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matricule, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Matricule, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateDeMiseEnCirculation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateDeMiseEnCirculation, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.DateDeMiseEnCirculation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeCarburant, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeCarburant, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeCarburant, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrixJournaliere, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrixJournaliere, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrixJournaliere, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Modeles Voitures</label>
            <div class="col-md-10">
                @{
                    CarRentt.Models.ApplicationDbContext db = new CarRentt.Models.ApplicationDbContext();
                    List<CarRentt.Models.Modele> listModele = db.Modeles.ToList();
                    <select name="MID" class="form-control">
                        @{
                            <option value="" disabled hidden selected>
                                trouver votre modele preferée
                            </option>
                            foreach (var item in listModele)
                            {
                                <option value="@item.ModeleID">
                                    @item.MarqueVoiture @item.SerieVoiture
                                </option>
                            }
                        }
                    </select>

                }
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="img" id="img" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarRentt/Areas/Admin/Views/GestionVoitures/Delete.cshtml
@model CarRentt.Models.Voiture

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Voiture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Modele.SerieVoiture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modele.SerieVoiture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Matricule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Matricule)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateDeMiseEnCirculation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateDeMiseEnCirculation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeCarburant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeCarburant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrixJournaliere)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrixJournaliere)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CarRentt/Areas/Admin/Views/GestionVoitures/Details.cshtml
@model CarRentt.Models.Voiture

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Voiture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Modele.SerieVoiture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modele.SerieVoiture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Matricule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Matricule)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateDeMiseEnCirculation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateDeMiseEnCirculation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeCarburant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeCarburant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrixJournaliere)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrixJournaliere)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VoitureID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CarRentt/Areas/Admin/Views/GestionVoitures/Edit.cshtml
@model CarRentt.Models.Voiture

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Voiture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VoitureID)

        <div class="form-group">
            @Html.LabelFor(model => model.Matricule, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matricule, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Matricule, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateDeMiseEnCirculation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateDeMiseEnCirculation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateDeMiseEnCirculation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeCarburant, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeCarburant, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeCarburant, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrixJournaliere, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrixJournaliere, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrixJournaliere, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModeleID, "ModeleID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ModeleID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModeleID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsAvailable, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarRentt/Areas/Admin/Views/GestionVoitures/Index.cshtml
@model IEnumerable<CarRentt.Models.Voiture>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modele.SerieVoiture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Matricule)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateDeMiseEnCirculation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeCarburant)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrixJournaliere)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        <img src="~/image/voitures/@item.Image"
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Modele.SerieVoiture)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Matricule)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DateDeMiseEnCirculation)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TypeCarburant)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PrixJournaliere)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.IsAvailable)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.VoitureID }) |
        @Html.ActionLink("Details", "Details", new { id = item.VoitureID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.VoitureID }) |
        @Html.ActionLink("Stocker", "Stocker", new { id = item.VoitureID }) |

    </td>
</tr>
}

</table>